In [1]:
import tensorflow as tf
import tensorflow.keras.models as models
import pickle
import pandas as pd 
import numpy as np

In [2]:
model = models.load_model('model.h5')

with open('label_encoder.pkl', 'rb') as f:
    label_encoder = pickle.load(f)
with open('oh_encoder.pkl', 'rb') as f:
    oh_encoder = pickle.load(f)
with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [3]:
input_data={
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 5000

}

In [4]:
geo_encoded = oh_encoder.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=oh_encoder.get_feature_names_out(['Geography']))

c:\Users\sarth\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [5]:
geo_encoded_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [6]:
input_df = pd.DataFrame([input_data])

In [8]:
input_df['Gender'] = label_encoder.transform(input_df['Gender'])

In [ ]:
input_df = pd.concat([input_df.drop(columns=['Geography']), geo_encoded_df], axis=1)

In [10]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,5000,1.0,0.0,0.0

In [12]:
input_scaled = scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -1.65923237,  1.00150113,
        -0.57946723, -0.57638802]])

In [13]:
prediction = model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 217ms/step

array([[0.06188221]], dtype=float32)

In [14]:
prediction_prob = prediction[0][0]
prediction_prob

0.06188221

In [15]:
if prediction_prob > 0.5:
    print("The customer is likely to churn.")
else:
    print("The customer is unlikely to churn.")

The customer is unlikely to churn.