In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')

In [3]:
data=data.drop(['RowNumber','CustomerId','Surname'], axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
label_encoder = LabelEncoder()
data['Gender'] = label_encoder.fit_transform(data['Gender'])

In [5]:
oh_encoder = OneHotEncoder()
geo_encoder = oh_encoder.fit_transform(data[['Geography']])
geo_encoder

<10000x3 sparse matrix of type '<class 'numpy.float64'>'
	with 10000 stored elements in Compressed Sparse Row format>

In [6]:
geo_encoded_df = pd.DataFrame(geo_encoder.toarray(), columns=oh_encoder.get_feature_names_out(['Geography']))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [7]:
data = pd.concat([data.drop('Geography', axis=1) ,geo_encoded_df], axis=1)

In [8]:
X=data.drop('EstimatedSalary', axis=1)
y=data['EstimatedSalary']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y , test_size=0.2, random_state=42)

In [10]:
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
with open ('label_encoder.pkl', 'wb') as f:
    pickle.dump(label_encoder, f)
with open ('oh_encoder.pkl', 'wb') as f:
    pickle.dump(oh_encoder, f)
with open ('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

c:\Users\sarth\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
## train this mode
from tensorflow.keras.callbacks import EarlyStopping
import datetime

log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

In [17]:
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [18]:
history = model.fit(
    X_train, y_train, validation_data=(X_test, y_test), epochs=100,
    callbacks = [tensorboard_callback, early_stopping_callback]
    )

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 100382.2344 - mae: 100382.2344 - val_loss: 98530.9766 - val_mae: 98530.9766
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 99670.5938 - mae: 99670.5938 - val_loss: 97082.8203 - val_mae: 97082.8203
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 97130.3359 - mae: 97130.3359 - val_loss: 93349.1250 - val_mae: 93349.1250
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 92096.6875 - mae: 92096.6875 - val_loss: 87067.4219 - val_mae: 87067.4219
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 84686.2500 - mae: 84686.2500 - val_loss: 78945.8906 - val_mae: 78945.8906
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 75941.1562 - mae: 75941.1562 - val_loss: 70280.0000 - val_mae: 70280.0000
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 67291.3672 - mae: 67291.3672 - val_loss: 62537.5938 - val_mae: 62537.5938
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 60094.0312 - mae: 60094.0312 - val_loss: 56782.2266 - val_mae: 56782.2266
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55091.8906 - mae: 55091.8906 - val_loss: 53279.7773 - val_mae: 53279.7773
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52261.0781 - mae: 52261.0781 - val_loss: 51646.5742 - val_mae: 51646.5742
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50960.8477 - mae: 50960.8477 - val_loss: 51020.7188 - val_mae: 51020.7188
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50454.9766 - mae: 50454.9766 - val_loss: 50843.5742 - val_mae: 50843.5742
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50287.1406 - mae: 50287.1406 - val_loss: 50779.9844 - val_mae: 50779.9844
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50206.7617 - mae: 50206.7617 - val_loss: 50740.5352 - val_mae: 50740.5352
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50150.7539 - mae: 50150.7539 - val_loss: 50704.0625 - val_mae: 50704.0625
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50103.1289 - mae: 50103.1289 - val_loss: 50675.1250 - val_mae: 50675.1250
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50067.1016 - mae: 50067.1016 - val_loss: 50637.4258 - val_mae: 50637.4258
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50029.8555 - mae: 50029.8555 - val_loss: 50605.0625 - val_mae: 50605.0625
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49991.4414 - mae: 49991.4414 - val_loss: 50578.6523 - val_mae: 50578.6523
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49958.2305 - mae: 49958.2305 - val_loss: 50544.7109 - val_mae: 50544.7109
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49930.3672 - mae: 49930.3672 - val_loss: 50538.9141 - val_mae: 50538.9141
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49904.1445 - mae: 49904.1445 - val_loss: 50517.5586 - val_mae: 50517.5586
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49879.8320 - mae: 49879.8320 - val_loss: 50513.9453 - val_mae: 50513.9453
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49852.9492 - mae: 49852.9492 - val_loss: 50497.8516 - val_mae: 50497.8516
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49835.6328 - mae: 49835.6328 - val_loss: 50484.5391 - val_mae: 50484.5391
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49814.3477 - mae: 49814.3477 - val_loss: 50468.7305 - val_mae: 50468.7305
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49801.5078 - mae: 49801.5078 - val_loss: 50457.7422 - val_mae: 50457.7422
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49777.7305 - mae: 49777.7305 - val_loss: 50453.0859 - val_mae: 50453.0859
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49761.6797 - mae: 49761.6797 - val_loss: 50434.9062 - val_mae: 50434.9062
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49745.4648 - mae: 49745.4648 - val_loss: 50436.3164 - val_mae: 50436.3164
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49732.8828 - mae: 49732.8828 - val_loss: 50434.7383 - val_mae: 50434.7383
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49719.3867 - mae: 49719.3867 - val_loss: 50421.2812 - val_mae: 50421.2812
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49704.0742 - mae: 49704.0742 - val_loss: 50408.9102 - val_mae: 50408.9102
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49690.5312 - mae: 49690.5312 - val_loss: 50395.8086 - val_mae: 50395.8086
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49679.0352 - mae: 49679.0352 - val_loss: 50394.2383 - val_mae: 50394.2383
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49667.6758 - mae: 49667.6758 - val_loss: 50390.3125 - val_mae: 50390.3125
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49657.2891 - mae: 49657.2891 - val_loss: 50379.7734 - val_mae: 50379.7734
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49645.2656 - mae: 49645.2656 - val_loss: 50375.8281 - val_mae: 50375.8281
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49632.3398 - mae: 49632.3398 - val_loss: 50378.9141 - val_mae: 50378.9141
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49621.5000 - mae: 49621.5000 - val_loss: 50365.7734 - val_mae: 50365.7734
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49613.8281 - mae: 49613.8281 - val_loss: 50362.7383 - val_mae: 50362.7383
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49604.0156 - mae: 49604.0156 - val_loss: 50366.2383 - val_mae: 50366.2383
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49593.0469 - mae: 49593.0469 - val_loss: 50360.2422 - val_mae: 50360.2422
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49583.5195 - mae: 49583.5195 - val_loss: 50367.3672 - val_mae: 50367.3672
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49578.7578 - mae: 49578.7578 - val_loss: 50361.6445 - val_mae: 50361.6445
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49567.0391 - mae: 49567.0391 - val_loss: 50347.0898 - val_mae: 50347.0898
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49556.1641 - mae: 49556.1641 - val_loss: 50358.9961 - val_mae: 50358.9961
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49548.8203 - mae: 49548.8203 - val_loss: 50357.3203 - val_mae: 50357.3203
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49542.8750 - mae: 49542.8750 - val_loss: 50347.8203 - val_mae: 50347.8203
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49534.8281 - mae: 49534.8281 - val_loss: 50354.5352 - val_mae: 50354.5352
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49525.4883 - mae: 49525.4883 - val_loss: 50355.0352 - val_mae: 50355.0352
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49518.5781 - mae: 49518.5781 - val_loss: 50360.6719 - val_mae: 50360.6719
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49512.9219 - mae: 49512.9219 - val_loss: 50351.1094 - val_mae: 50351.1094
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49507.3438 - mae: 49507.3438 - val_loss: 50344.2188 - val_mae: 50344.2188
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49497.8047 - mae: 49497.8047 - val_loss: 50347.8750 - val_mae: 50347.8750
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49492.1328 - mae: 49492.1328 - val_loss: 50347.1758 - val_mae: 50347.1758
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49487.6094 - mae: 49487.6094 - val_loss: 50348.4961 - val_mae: 50348.4961
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49479.5430 - mae: 49479.5430 - val_loss: 50354.9922 - val_mae: 50354.9922
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49473.7930 - mae: 49473.7930 - val_loss: 50342.6602 - val_mae: 50342.6602
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49465.5234 - mae: 49465.5234 - val_loss: 50351.0508 - val_mae: 50351.0508
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49460.3086 - mae: 49460.3086 - val_loss: 50355.7305 - val_mae: 50355.7305
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49458.1172 - mae: 49458.1172 - val_loss: 50355.0312 - val_mae: 50355.0312
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49451.3125 - mae: 49451.3125 - val_loss: 50353.1367 - val_mae: 50353.1367
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49442.5586 - mae: 49442.5586 - val_loss: 50351.5000 - val_mae: 50351.5000
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49438.5039 - mae: 49438.5039 - val_loss: 50354.5117 - val_mae: 50354.5117
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49435.6602 - mae: 49435.6602 - val_loss: 50355.2109 - val_mae: 50355.2109
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49430.3906 - mae: 49430.3906 - val_loss: 50357.1250 - val_mae: 50357.1250
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49422.4375 - mae: 49422.4375 - val_loss: 50356.5000 - val_mae: 50356.5000
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49418.4102 - mae: 49418.4102 - val_loss: 50350.2461 - val_mae: 50350.2461

In [19]:
%load_ext tensorboard

In [21]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 4988), started 0:00:14 ago. (Use '!kill 4988' to kill it.)

In [22]:
test_loss, test_mae = model.evaluate(X_test, y_test)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50342.6602 - mae: 50342.6602
Test Loss: 50342.66015625, Test MAE: 50342.66015625

In [ ]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

: